apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dev-app
  labels:
    app: todo-dev-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-dev-app
  template:
    metadata:
      labels:
        app: todo-dev-app
    spec:
      containers:
      - name: todo-dev-app
        image: soma1999/todo-dev-app
        ports:
        - containerPort: 8000
